# Numpy exercises


#### 1. Import the numpy package under the name `np`

#### Import արեք numpy module-ը np անունով:

In [1]:
import numpy as np

#### 2. Create a numpy array of size 10 filled with zeros. 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array:

In [2]:
a=np.array([0,0,0,0,0,0,0,0,0,0])

#### 3.  How to get the documentation of the numpy add function? 

#### Նայեք numpy-ի add ֆունկցիայի դոկումենտացիան:

#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array, որի 5րդ արժեքը 1 է:

In [4]:
b=np.array([0,0,0,0,1,0,0,0,0,0])
b

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 5.  Create a vector with values ranging from 10 to 49

#### Ստեղծեք 10-ից 49 հաջորդական թվերով numpy array:

In [37]:
c=np.arange(10,50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 6.  Reverse the numpy array ranging from 0 to 50. 

#### Ստեղծեք 0-ից 50 հաջորդական թվերով numpy array և տպեք այն շրջած ձևով:

In [241]:
c=np.arange(-50,1)*(-1)
c

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

#### Ստեղծեք 0-ից 8 հաջորդական թվերով 3x3 numpy array

In [35]:
c=np.array([range(0,9)])
c.shape=(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### Տրված է \[1,2,0,0,4,0\] numpy array-ը, գտեք ոչ-զրոյական արժեքներով տարրերի կոորդինատները:

In [57]:
a=np.array([1,2,0,0,4,0])
for x in range(0,len(a)):
    if a[x]!=0:
        print(x)

0
1
4


#### 9. Create a 3x3x3 array with random integers from 1 to 20

#### Ստեղծեք 1-ից 20 պատահական թվերով լցված (3x3x3) չափանի numpy array:

In [96]:
c=np.random.randint(1,20,27)
c.reshape(3,3,3)

array([[[ 4, 18, 18],
        [18, 10,  3],
        [ 8, 10, 19]],

       [[ 9,  2, 13],
        [ 4,  8,  4],
        [ 7,  4,  4]],

       [[ 4,  2, 10],
        [10, 18,  2],
        [ 9, 11, 12]]])

#### 10. Create a 10x10 array with random values and find the minimum and maximum values 

#### Ստեղծեք պատահական թվերով լցված (10x10) չափանի numpy array ու տպեք դրա փոքրագույն ու մեծագույն արժեքները:

In [103]:
c=np.empty((10,10), dtype=int)
print(c)
print(c.max(),c.min())

[[         -1  2147483647           1           0         556           0
            1           0         804           0]
 [        411 -2147482368         876           0         411 -2147481856
          724           0         411           0]
 [        808           0         411 -2147483136         752           0
          411           0        1084           0]
 [        411           0        1152           0         411           0
         1104           0         411           0]
 [       1144           0         411           0        1132           0
          411 -2147481599        1120           0]
 [        411           0        1084           0         411 -2147482112
         1152           0         411           0]
 [       1104           0         411           0        1144           0
          411           0        1132           0]
 [        411           0        1120           0         411           0
         1152           0           4 -2147481096]


#### 11. Create a random vector of size 30 and find the mean value 

#### Ստեղծեք 30 չափանի պատահական թվերով լցված numpy array ու տպեք դրա միջին արժեքը:

In [146]:
c=np.empty((1,30), dtype=float)

print(c,c.sum()/30)

[[9.54994084e-312 9.58487353e-322 0.00000000e+000 0.00000000e+000
  0.00000000e+000 5.02034658e+175 3.73466425e-033 1.31403677e-047
  2.67659675e+184 3.29526381e-032 5.01163188e+217 5.49419094e-143
  9.80058441e+252 1.04857885e-142 2.14027814e+161 5.04621383e+180
  4.50618615e-144 7.79952704e-143 2.09097143e-076 2.02545129e-052
  1.09360549e-042 3.34790390e-061 1.41529402e+161 9.16651763e-072
  5.38183348e+097 5.65043541e-038 2.91009542e+126 9.30350598e+199
  3.67152475e-062 1.58268989e-319]] 3.2668614689218266e+251


#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

#### Ստեղծեք 0-ից 10 հաջորդական թվերով numpy array: Տպեք բոլոր արժեքները, որոնք 3-ից 8 միջակայքում են:

In [149]:
c=np.arange(11)
for x in c:
    if x>2 and x<9:
        print(x)

3
4
5
6
7
8


#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

#### Ստեղծեք 1-ից 10 պատահական ամբողջ թվերով լցված 20 չափանի numpy array: Բազմապատկեք 5-ից փոքր արժեք ունեցող տարերրը 2-ով ու տպեք արդյունքում ստացված array-ը:

In [154]:
a=np.random.randint(1,11,20)
for x in range(0,len(a)):
    if a[x]<5:
        a[x]*=2
a        

array([ 8,  8,  4,  7,  7,  5,  7, 10,  9,  8,  8,  6,  8,  8,  7,  6,  8,
        4,  6,  8])

#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

#### Տրված է [1, 5, 6, 2, -2, 23, 45] numpy array-ը, գտեք 2-ի բաժանվող տարրերի կոորդինատները:

In [157]:
a=np.array([1, 5, 6, 2, -2, 23, 45])
for x in range(0,len(a)):
    if a[x]%2==0:
        print(x)

2
3
4


#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

#### Ստեղծեք 1-ից 20 հաջորդական թվերով լցված numpy array, տպեք բոլոր 3-ի բաժանվող տարրերի արժեքները:

In [160]:
a=np.arange(21)
for x in a:
    if x%3==0:
        print(x)

0
3
6
9
12
15
18


#### 16. Create a 5x5 matrix with each row values ranging from 0 to 4 

#### Ստեղծեք 5x5 numpy array, որի ամեն տող իրենից ներկայացնում է 0-ից 4 հաջորդական թվեր:

In [165]:
a=np.array([1,2,3,4]*4).reshape(4,4)
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

#### 17. Գեներացրեք 1-ից 10 պատահական թվեր ու ստեղծեք (3, 5) չափերով numpy array-ը

In [170]:
a=np.random.randint(1,11,15).reshape(3,5)
a

array([[ 6,  8,  8,  3,  6],
       [ 5,  7,  4,  1,  1],
       [10,  8,  8,  9,  6]])

#### 18. Ստեղծեք 10 չափի 0-ներով լցված numpy array ու փոխարինեք դրա 5-րդ արժեքը 3 թվով։

In [167]:
a=np.array([0]*10)
a[4]=3
a

array([0, 0, 0, 0, 3, 0, 0, 0, 0, 0])

#### 19. Ստեղծեք 3-ից 15 թվերից բաղկացած numpy array ([3, 4 … 13, 14])

In [172]:
a=np.arange(3,15)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 20. Գրեք ֆունկցիա, որը ստանում է numpy array ու բաժանում է դրա բոլոր արժեքները 2-ի այնքան ժամանակ մինչև որ դրանց միջին արժեքը լինի <=5։ Այնուհետև, հենց միջին արժեքը դառնում է <=5, ֆունկցիան վերադարձնում է փոփոխված numpy array-ը։

In [184]:
a=np.array([range(10,20)], dtype=float)
print(a)
def fun(x):
    while x.sum()/len(x)>5:
        x/=2
    print(x)    
fun(a)        

[[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
[[0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125 0.5625
  0.59375]]


#### 21. Գրեք ֆունկցիա, որը ստանում է 1-ից 10 պատահական թվերով լցված 5x4 numpy array ու վերադարձնում է 4 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի սյուներն են։ Գրեք նմանատիպ ֆունկցիա, որը վերադարձնում է 5 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի տողերն են։

In [220]:
a=np.random.randint(1,11,20).reshape(5,4)
print(a)
def fun1(x):
    yield x[...,0]
    yield x[...,1]
    yield x[...,2]
    yield x[...,3]
def fun2(x):
    yield x[0,...]
    yield x[1,...]
    yield x[2,...]
    yield x[3,...]
    yield x[4,...]
print(list(fun1(a)))

[[ 7  2  3  2]
 [ 5  7  9 10]
 [ 5  6  9  6]
 [ 8  7  9  6]
 [ 5 10  1  1]]
[array([7, 5, 5, 8, 5]), array([ 2,  7,  6,  7, 10]), array([3, 9, 9, 9, 1]), array([ 2, 10,  6,  6,  1])]
