In [3]:
import numpy as np
a=np.random.randint(1,11,15).reshape(3,5)
a

array([[ 4,  9, 10,  7,  4],
       [ 5,  8,  5,  7, 10],
       [10,  2,  2,  1,  3]])

In [4]:
a=np.array([0]*10)
a[4]=3
a

array([0, 0, 0, 0, 3, 0, 0, 0, 0, 0])

In [5]:
a=np.arange(3,15)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
a=np.array([1,3,5,2,4,5])
a.reshape(3,2)

array([[1, 3],
       [5, 2],
       [4, 5]])

In [7]:
a.reshape(2,3)

array([[1, 3, 5],
       [2, 4, 5]])

In [8]:
a=np.array([range(10,20)], dtype=float)
print(a)
def fun(x):
    while x.sum()/len(x)>5:
        x/=2
    print(x)    
fun(a)        

[[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
[[0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125 0.5625
  0.59375]]


In [ ]:
a=np.random.randint(1,11,20).reshape(5,4)
print(a)
def fun1(x):
    yield x[...,0]
    yield x[...,1]
    yield x[...,2]
    yield x[...,3]
def fun2(x):
    yield x[0,...]
    yield x[1,...]
    yield x[2,...]
    yield x[3,...]
    yield x[4,...]
print(list(fun1(a)))